/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.AbstractDAO;
import Controlador.conexion;
import Modelo.Paciente;
import Reportes.PacientesR;
import static Vista.iFraAdm.createImageIcon;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import util.Fecha;

/**
 *
 * @author usuario
 */
public class dlgPacOpReporte extends javax.swing.JDialog {
//    private boolean ordId,orNom,asc, desc,todos,algunos;
    private boolean ordProf,ordSexo,ordF,ordEdad,ordPac,asc,desc,todos,algunos;
    int anio,mes;
    Fecha f;
    ImageIcon icon = createImageIcon("img/ayuda_.png");
    /**
     * Creates new form dlgPacOpReporte
     */
    public dlgPacOpReporte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        grupoBotones();
        arranque();
//        ordId=orNom=asc=desc=todos=algunos=false;
        ordProf=ordSexo=ordF=ordEdad=ordPac=asc=desc=todos=algunos=false;
        anio=mes=0;
        SLetras(txtNomPac);
        SLetras(txtNomProfesion);
        f=null;
        SNroEntero(this.txtCant);
        SNroEntero(txtEdadDesde);
        SNroEntero(txtEdadHasta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGpMostrar = new javax.swing.ButtonGroup();
        btnGpOrdenar = new javax.swing.ButtonGroup();
        btnGpOrdenarTipo = new javax.swing.ButtonGroup();
        panelMostrar1 = new javax.swing.JPanel();
        panelMostrar = new javax.swing.JPanel();
        rbtXRegistros = new javax.swing.JRadioButton();
        rbtMostrarTodos = new javax.swing.JRadioButton();
        txtCant = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        panelOrdenar = new javax.swing.JPanel();
        rbtNroPac = new javax.swing.JRadioButton();
        rbtFNac = new javax.swing.JRadioButton();
        rbtPac = new javax.swing.JRadioButton();
        rbtEdad = new javax.swing.JRadioButton();
        rbtIngreso = new javax.swing.JRadioButton();
        panelTipo = new javax.swing.JPanel();
        rbtAsc = new javax.swing.JRadioButton();
        rbtDesc = new javax.swing.JRadioButton();
        panelFiltro = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        cboSexo = new javax.swing.JComboBox();
        lblDe = new javax.swing.JLabel();
        txtEdadDesde = new javax.swing.JTextField();
        lblA = new javax.swing.JLabel();
        txtEdadHasta = new javax.swing.JTextField();
        lblAnios = new javax.swing.JLabel();
        lblProfesion = new javax.swing.JLabel();
        txtNomPac = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnAyuda = new javax.swing.JButton();
        lblAnio = new javax.swing.JLabel();
        chooserAnio = new com.toedter.calendar.JYearChooser();
        lblMes = new javax.swing.JLabel();
        chooserMes = new com.toedter.calendar.JMonthChooser();
        chkAnio = new javax.swing.JCheckBox();
        chkMes = new javax.swing.JCheckBox();
        chkRangoEdad = new javax.swing.JCheckBox();
        txtNomProfesion = new javax.swing.JTextField();
        chkPaciente = new javax.swing.JCheckBox();
        chkProfesion = new javax.swing.JCheckBox();
        chkSexo = new javax.swing.JCheckBox();
        lblEstadoCivil = new javax.swing.JLabel();
        cboEstadoCivil = new javax.swing.JComboBox();
        chkEstadoCivil = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones de Listado");
        setResizable(false);

        panelMostrar1.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        panelMostrar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        panelMostrar.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        panelMostrar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Mostrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 24))); // NOI18N

        rbtXRegistros.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        rbtXRegistros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtXRegistros.setText("Listrar ");
        rbtXRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtXRegistrosActionPerformed(evt);
            }
        });

        rbtMostrarTodos.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        rbtMostrarTodos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtMostrarTodos.setText("Listar todos.");
        rbtMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMostrarTodosActionPerformed(evt);
            }
        });

        txtCant.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCant.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("registros.");

        btnVer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Preview.png"))); // NOI18N
        btnVer.setText("VER");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMostrarLayout = new javax.swing.GroupLayout(panelMostrar);
        panelMostrar.setLayout(panelMostrarLayout);
        panelMostrarLayout.setHorizontalGroup(
            panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(rbtXRegistros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(72, 72, 72)
                .addComponent(rbtMostrarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        panelMostrarLayout.setVerticalGroup(
            panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarLayout.createSequentialGroup()
                .addGroup(panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtXRegistros)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(rbtMostrarTodos)
                    .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOrdenar.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        panelOrdenar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Ordenar por", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 24))); // NOI18N

        rbtNroPac.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        rbtNroPac.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtNroPac.setText("Nro");
        rbtNroPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNroPacActionPerformed(evt);
            }
        });

        rbtFNac.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        rbtFNac.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtFNac.setText("Fecha Nac.");
        rbtFNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFNacActionPerformed(evt);
            }
        });

        rbtPac.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        rbtPac.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtPac.setText("Paciente");
        rbtPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPacActionPerformed(evt);
            }
        });

        rbtEdad.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        rbtEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtEdad.setText("Edad");
        rbtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEdadActionPerformed(evt);
            }
        });

        rbtIngreso.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        rbtIngreso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtIngreso.setText("Ingreso");
        rbtIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOrdenarLayout = new javax.swing.GroupLayout(panelOrdenar);
        panelOrdenar.setLayout(panelOrdenarLayout);
        panelOrdenarLayout.setHorizontalGroup(
            panelOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdenarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtNroPac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtPac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtFNac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtIngreso))
        );
        panelOrdenarLayout.setVerticalGroup(
            panelOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdenarLayout.createSequentialGroup()
                .addGroup(panelOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtNroPac)
                    .addComponent(rbtFNac)
                    .addComponent(rbtPac)
                    .addComponent(rbtEdad)
                    .addComponent(rbtIngreso))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        panelTipo.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        panelTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Tipo de Ordenamiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 24))); // NOI18N

        rbtAsc.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        rbtAsc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtAsc.setText("Ascendente");
        rbtAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAscActionPerformed(evt);
            }
        });

        rbtDesc.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        rbtDesc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtDesc.setText("Descendente");
        rbtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTipoLayout = new javax.swing.GroupLayout(panelTipo);
        panelTipo.setLayout(panelTipoLayout);
        panelTipoLayout.setHorizontalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtAsc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtDesc)
                .addContainerGap())
        );
        panelTipoLayout.setVerticalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoLayout.createSequentialGroup()
                .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtAsc)
                    .addComponent(rbtDesc))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        panelFiltro.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        panelFiltro.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Filtro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 24))); // NOI18N

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFecha.setText(" Fecha Nac:");
        lblFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFecha.setOpaque(true);

        lblPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPaciente.setText(" Paciente: ");
        lblPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPaciente.setOpaque(true);

        lblSexo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSexo.setText(" Sexo: ");
        lblSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblSexo.setOpaque(true);

        lblEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEdad.setText(" Edad: ");
        lblEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEdad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblEdad.setOpaque(true);

        cboSexo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ambos", "Femenino", "Masculino" }));
        cboSexo.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblDe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDe.setText("De");

        txtEdadDesde.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblA.setText("a");

        txtEdadHasta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblAnios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAnios.setText("años");

        lblProfesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblProfesion.setText(" Profesión:");
        lblProfesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblProfesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblProfesion.setOpaque(true);

        txtNomPac.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomPac.setEnabled(false);

        jPanel5.setBackground(java.awt.SystemColor.inactiveCaptionBorder);

        btnAyuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/48_ayuda.png"))); // NOI18N
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAyuda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, Short.MAX_VALUE)
        );

        lblAnio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAnio.setText(" Año:");
        lblAnio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAnio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAnio.setOpaque(true);

        lblMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMes.setText(" Mes:");
        lblMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMes.setOpaque(true);

        chooserMes.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        chkAnio.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        chkAnio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAnioActionPerformed(evt);
            }
        });

        chkMes.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        chkMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMesActionPerformed(evt);
            }
        });

        chkRangoEdad.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        chkRangoEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkRangoEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRangoEdadActionPerformed(evt);
            }
        });

        txtNomProfesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomProfesion.setEnabled(false);

        chkPaciente.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        chkPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPacienteActionPerformed(evt);
            }
        });

        chkProfesion.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        chkProfesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProfesionActionPerformed(evt);
            }
        });

        chkSexo.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        chkSexo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSexoActionPerformed(evt);
            }
        });

        lblEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEstadoCivil.setText("Estado Civil: ");
        lblEstadoCivil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEstadoCivil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblEstadoCivil.setOpaque(true);

        cboEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Casada/o", "Soltera/o", "Separada/o", "Viuda/o" }));
        cboEstadoCivil.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        chkEstadoCivil.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        chkEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstadoCivilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFiltroLayout = new javax.swing.GroupLayout(panelFiltro);
        panelFiltro.setLayout(panelFiltroLayout);
        panelFiltroLayout.setHorizontalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEstadoCivil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltroLayout.createSequentialGroup()
                        .addComponent(cboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkEstadoCivil)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelFiltroLayout.createSequentialGroup()
                        .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFiltroLayout.createSequentialGroup()
                                .addComponent(lblMes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooserMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkMes)
                                .addGap(16, 16, 16)
                                .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chooserAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkAnio)
                                .addGap(27, 27, 27)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFiltroLayout.createSequentialGroup()
                                .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkSexo))
                            .addGroup(panelFiltroLayout.createSequentialGroup()
                                .addComponent(lblDe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEdadDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEdadHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAnios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkRangoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFiltroLayout.createSequentialGroup()
                                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomPac, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkProfesion)
                                    .addComponent(chkPaciente))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelFiltroLayout.setVerticalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFiltroLayout.createSequentialGroup()
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(chooserAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chooserMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkMes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNomPac, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboSexo)
                    .addGroup(panelFiltroLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboEstadoCivil)))
                    .addGroup(panelFiltroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDe)
                        .addComponent(txtEdadDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblA)
                        .addComponent(txtEdadHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAnios))
                    .addComponent(chkRangoEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblProfesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNomProfesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/note.png"))); // NOI18N
        jLabel1.setText("                Listado de Pacientes");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout panelMostrar1Layout = new javax.swing.GroupLayout(panelMostrar1);
        panelMostrar1.setLayout(panelMostrar1Layout);
        panelMostrar1Layout.setHorizontalGroup(
            panelMostrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrar1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelMostrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMostrar1Layout.createSequentialGroup()
                        .addComponent(panelOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFiltro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelMostrar1Layout.setVerticalGroup(
            panelMostrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMostrar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMostrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMostrar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMostrar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        String ini="<html><font size=5 style=color:black;> "; 
        String mensaje= ini + " Si no selecciona ninguna opción para filtrado de datos, se mostraran \n"
                + ini + "\"todos los pacientes registrados.\"";     
        JOptionPane.showMessageDialog(this, mensaje, "AYUDA",JOptionPane.INFORMATION_MESSAGE, icon);
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void chkAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAnioActionPerformed
        if(this.chkAnio.isSelected()){
            this.chooserAnio.setEnabled(true);
            this.lblAnio.setEnabled(true);
            if(!lblFecha.isEnabled())this.lblFecha.setEnabled(true);
        }else{
            this.chooserAnio.setEnabled(false);
            f=new Fecha();
            chooserAnio.setYear(f.getAnio());
            this.lblAnio.setEnabled(false);
            chkAnio.setSelected(false);
            if(lblFecha.isEnabled())this.lblFecha.setEnabled(false);
        }
    }//GEN-LAST:event_chkAnioActionPerformed

    private void chkMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMesActionPerformed
        if(this.chkMes.isSelected()){
            this.chooserMes.setEnabled(true);
            this.lblMes.setEnabled(true);
            if(!lblFecha.isEnabled())this.lblFecha.setEnabled(true);            
        }else{
            this.chooserMes.setEnabled(false);
            this.lblMes.setEnabled(false);
            f=new Fecha();
            chooserMes.setMonth(f.getMes()-1);
            chkMes.setSelected(false);
            if(lblFecha.isEnabled())this.lblFecha.setEnabled(false);
        }
    }//GEN-LAST:event_chkMesActionPerformed

    private void chkRangoEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRangoEdadActionPerformed
         if(this.chkRangoEdad.isSelected()){
            this.lblEdad.setEnabled(true);
            this.lblAnios.setEnabled(true);
            this.lblDe.setEnabled(true);
            this.lblA.setEnabled(true);
            this.txtEdadDesde.setEnabled(true);
            this.txtEdadHasta.setEnabled(true);
        }else{
            this.lblEdad.setEnabled(false);
            this.lblAnios.setEnabled(false);
            this.lblDe.setEnabled(false);
            this.lblA.setEnabled(false);
            this.txtEdadDesde.setEnabled(false);
            this.txtEdadHasta.setEnabled(false);
            this.txtEdadDesde.setText(null);
            this.txtEdadHasta.setText(null);
        }
    }//GEN-LAST:event_chkRangoEdadActionPerformed

    private void chkPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPacienteActionPerformed
        if(this.chkPaciente.isSelected()){
            this.txtNomPac.setEnabled(true);
            this.lblPaciente.setEnabled(true);
        }else{
            this.txtNomPac.setEnabled(false);
            this.txtNomPac.setText(null);
            this.lblPaciente.setEnabled(false);
        }
    }//GEN-LAST:event_chkPacienteActionPerformed

    private void chkProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProfesionActionPerformed
        if(this.chkProfesion.isSelected()){
            this.lblProfesion.setEnabled(true);
            this.txtNomProfesion.setEnabled(true);
        }else{
            this.lblProfesion.setEnabled(false);
            this.txtNomProfesion.setEnabled(false);
            this.txtNomProfesion.setText(null);
        }
    }//GEN-LAST:event_chkProfesionActionPerformed

    private void chkSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSexoActionPerformed
        if(this.chkSexo.isSelected()){
            this.lblSexo.setEnabled(true);
            this.cboSexo.setEnabled(true);
        }else{
           this.lblSexo.setEnabled(false);
           this.cboSexo.setEnabled(false);
           cboSexo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_chkSexoActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed

        if(validar()){
            this.dispose();
            informe(); //segun opcion es la tabla que se muestra
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void chkEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstadoCivilActionPerformed
        if(this.chkEstadoCivil.isSelected()){
            this.lblEstadoCivil.setEnabled(true);
            this.cboEstadoCivil.setEnabled(true);
        }else{
            this.lblEstadoCivil.setEnabled(false);
            this.cboEstadoCivil.setEnabled(false);
        }
    }//GEN-LAST:event_chkEstadoCivilActionPerformed

    private void rbtXRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtXRegistrosActionPerformed
        algunos=rbtXRegistros.isSelected();
        todos = !algunos;
        if(algunos)
            txtCant.setEnabled(true);
    }//GEN-LAST:event_rbtXRegistrosActionPerformed

    private void rbtMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMostrarTodosActionPerformed
        todos = this.rbtMostrarTodos.isSelected();
        algunos=!todos;
        txtCant.setEnabled(false);
        txtCant.setText(null);

    }//GEN-LAST:event_rbtMostrarTodosActionPerformed

    private void rbtNroPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNroPacActionPerformed
        ordPac = this.rbtNroPac.isSelected();
        ordProf=ordSexo=ordF=ordEdad=!ordPac;
    }//GEN-LAST:event_rbtNroPacActionPerformed

    private void rbtPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPacActionPerformed
        ordProf = this.rbtPac.isSelected();
        ordPac=ordSexo=ordF=ordEdad=!ordProf;
    }//GEN-LAST:event_rbtPacActionPerformed

    private void rbtFNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFNacActionPerformed
        ordEdad = this.rbtFNac.isSelected();
        ordPac=ordSexo=ordF=ordProf=!ordEdad;
    }//GEN-LAST:event_rbtFNacActionPerformed

    private void rbtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEdadActionPerformed
        ordF = this.rbtEdad.isSelected();
        ordPac=ordSexo=ordProf=ordEdad=!ordF;
    }//GEN-LAST:event_rbtEdadActionPerformed

    private void rbtIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtIngresoActionPerformed
        ordSexo = this.rbtIngreso.isSelected();
        ordPac=ordProf=ordEdad=ordF=!ordSexo;
    }//GEN-LAST:event_rbtIngresoActionPerformed

    private void rbtAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAscActionPerformed
        asc = this.rbtAsc.isSelected();
        desc = !asc;
    }//GEN-LAST:event_rbtAscActionPerformed

    private void rbtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDescActionPerformed
        desc = this.rbtDesc.isSelected();
        asc = !desc;
    }//GEN-LAST:event_rbtDescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgPacOpReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgPacOpReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgPacOpReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgPacOpReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgPacOpReporte dialog = new dlgPacOpReporte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.ButtonGroup btnGpMostrar;
    private javax.swing.ButtonGroup btnGpOrdenar;
    private javax.swing.ButtonGroup btnGpOrdenarTipo;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox cboEstadoCivil;
    private javax.swing.JComboBox cboSexo;
    private javax.swing.JCheckBox chkAnio;
    private javax.swing.JCheckBox chkEstadoCivil;
    private javax.swing.JCheckBox chkMes;
    private javax.swing.JCheckBox chkPaciente;
    private javax.swing.JCheckBox chkProfesion;
    private javax.swing.JCheckBox chkRangoEdad;
    private javax.swing.JCheckBox chkSexo;
    private com.toedter.calendar.JYearChooser chooserAnio;
    private com.toedter.calendar.JMonthChooser chooserMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblAnios;
    private javax.swing.JLabel lblDe;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblProfesion;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JPanel panelFiltro;
    private javax.swing.JPanel panelMostrar;
    private javax.swing.JPanel panelMostrar1;
    private javax.swing.JPanel panelOrdenar;
    private javax.swing.JPanel panelTipo;
    private javax.swing.JRadioButton rbtAsc;
    private javax.swing.JRadioButton rbtDesc;
    private javax.swing.JRadioButton rbtEdad;
    private javax.swing.JRadioButton rbtFNac;
    private javax.swing.JRadioButton rbtIngreso;
    private javax.swing.JRadioButton rbtMostrarTodos;
    private javax.swing.JRadioButton rbtNroPac;
    private javax.swing.JRadioButton rbtPac;
    private javax.swing.JRadioButton rbtXRegistros;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtEdadDesde;
    private javax.swing.JTextField txtEdadHasta;
    private javax.swing.JTextField txtNomPac;
    private javax.swing.JTextField txtNomProfesion;
    // End of variables declaration//GEN-END:variables


private void grupoBotones(){
        this.btnGpMostrar=new ButtonGroup();
        this.btnGpMostrar.add(rbtXRegistros);
        this.btnGpMostrar.add(rbtMostrarTodos);
        btnGpMostrar.clearSelection();
        this.btnGpOrdenar=new ButtonGroup();
        this.btnGpOrdenar.add(this.rbtEdad);
        this.btnGpOrdenar.add(this.rbtIngreso);
        this.btnGpOrdenar.add(this.rbtNroPac);
        this.btnGpOrdenar.add(this.rbtPac);
        this.btnGpOrdenar.add(this.rbtFNac);
        btnGpOrdenar.clearSelection();
        this.btnGpOrdenarTipo=new ButtonGroup();
        this.btnGpOrdenarTipo.add(this.rbtDesc);
        this.btnGpOrdenarTipo.add(this.rbtAsc);
        btnGpOrdenarTipo.clearSelection();
    }
    
private void arranque(){
    EnableForm(panelFiltro, false);
//    EnableForm(panelFiltro, false);
    EnableChk(true);
    this.chooserAnio.setEnabled(false);
    this.chooserMes.setEnabled(false);
    this.btnAyuda.setEnabled(true);
}

public void EnableChk(boolean op){
      this.chkAnio.setEnabled(op);
      this.chkMes.setEnabled(op);
      this.chkProfesion.setEnabled(op);
      this.chkRangoEdad.setEnabled(op);
      this.chkPaciente.setEnabled(op);
      this.chkEstadoCivil.setEnabled(op);
      this.chkSexo.setEnabled(op);
  }

public boolean validar(){
    String tit="Atención"; String msj;
    boolean res=true;
        
    if(!this.chkAnio.isSelected())
        anio=0;
    else
        anio=chooserAnio.getYear();
    if(!this.chkMes.isSelected())
        mes=0;
    else
        mes=this.chooserMes.getMonth()+1;
    
    if(this.chkPaciente.isSelected() && (txtNomPac.getText().trim()).length()==0){
      msj="<html><font size=5 style=color:red;>Paciente. Dato Requerido.";
      JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
      txtNomPac.grabFocus();
      return false;
    }
    
    if(this.chkRangoEdad.isSelected() && (txtEdadDesde.getText().trim()).length()==0){
      msj="<html><font size=5 style=color:red;>Edad desde. Dato Requerido.";
      JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
      txtEdadDesde.grabFocus();
      return false;
    } 
    
    if(this.chkRangoEdad.isSelected() && (txtEdadHasta.getText().trim()).length()==0){
      msj="<html><font size=5 style=color:red;>Edad hasta. Dato Requerido.";
      JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
      txtEdadHasta.grabFocus();
      return false;
    }
    
    if(this.chkRangoEdad.isSelected() && ((txtEdadHasta.getText().trim()).length())<((txtEdadDesde.getText().trim()).length())){
      msj="<html><font size=5 style=color:red;>Edad 1 debe ser menor o igual que Edad 2.";
      JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
      txtEdadDesde.grabFocus();
      return false;
    }

    if(this.chkProfesion.isSelected() && (txtNomProfesion.getText().trim()).length()==0){
      msj="<html><font size=5 style=color:red;>Profesión/Ocupación. Dato Requerido.";
      JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
      txtNomProfesion.grabFocus();
      return false;
    }
    
    if(!this.rbtNroPac.isSelected() && !this.rbtPac.isSelected() && !this.rbtFNac.isSelected() && !this.rbtEdad.isSelected() && !this.rbtIngreso.isSelected()){
        msj="<html><font size=5 style=color:red;>Ordenar por.. Dato Requerido.";
        JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
        rbtNroPac.grabFocus();
      return false;
    }
    
    if(!this.rbtAsc.isSelected() && !this.rbtDesc.isSelected()){
      msj="<html><font size=5 style=color:red;>Tipo de Ordenenamiento.. Dato Requerido.";
      JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
      rbtAsc.grabFocus();
      return false;
    }
    if(!this.rbtXRegistros.isSelected() && !this.rbtMostrarTodos.isSelected()){
      msj="<html><font size=5 style=color:red;>Opción de muestra. Dato Requerido.";
      JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
      rbtXRegistros.grabFocus();
      return false;
    }
    if(this.rbtXRegistros.isSelected() && (txtCant.getText().trim()).length()==0){
      msj="<html><font size=5 style=color:red;>Cant de registros a mostrar. Dato Requerido.";
      JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
      txtCant.grabFocus();
      return false;
    }
    
    return res;
}

public void informe(){
    try {
        int c, campo, ED, EH; String nomP,nomProf,s,ec, ord;
        campo=1; ord="ASC";
        if(!txtCant.getText().isEmpty()) c=Integer.parseInt(txtCant.getText());
            else c=cantRegPac();
        if(!txtNomPac.getText().isEmpty()) nomP=txtNomPac.getText();
            else nomP="";       
        if(!txtNomProfesion.getText().isEmpty()) nomProf=txtNomProfesion.getText();
            else nomProf="";    
        if(!cboSexo.getSelectedItem().equals("Ambos")) s=cboSexo.getSelectedItem().toString();
            else s="";
        if(!cboEstadoCivil.getSelectedItem().equals("Todos")) ec=cboEstadoCivil.getSelectedItem().toString();
            else ec="";
        if(!txtEdadDesde.getText().isEmpty()) ED=Integer.parseInt(txtEdadDesde.getText());
            else ED=0;
        if(!txtEdadHasta.getText().isEmpty()) EH=Integer.parseInt(txtEdadHasta.getText());
            else EH=0;

        if((ordPac && asc && todos) || (ordPac && asc && algunos)){campo=1; ord="ASC";}
        if((ordPac && desc && todos) || (ordPac && desc && algunos)){campo=1; ord="DESC";}
        if((ordProf && desc && todos) || (ordProf && desc && algunos)){campo=2; ord="DESC";}
        if((ordProf && asc && todos) || (ordProf && asc && algunos)) {campo=2; ord="ASC";}            
        if((ordF && desc && todos) || (ordF && desc && algunos)){campo=3; ord="DESC";}
        if((ordF && asc && todos) || (ordF && asc && algunos)) {campo=3; ord="ASC";}
        if((ordEdad && desc && todos) || (ordEdad && desc && algunos)){campo=4; ord="DESC";}
        if((ordEdad && asc && todos) || (ordEdad && asc && algunos)) {campo=4; ord="ASC";} 
        if((ordSexo && desc && todos) || (ordSexo && desc && algunos)){campo=5; ord="DESC";}
        if((ordSexo && asc && todos) || (ordSexo && asc && algunos)) {campo=5; ord="ASC";}
        
        List pacList = new ArrayList();
        List<PacientesR> lista = conexion.getInstance().getPacR(campo, ord, c, anio,mes,nomP,nomProf,ED,EH,s,ec);
//        JOptionPane.showMessageDialog(this, lista);
        String id, des, fechaNac, edad, fechaAlta;    
        if(!lista.isEmpty()){
            for (Iterator<PacientesR> it = lista.iterator(); it.hasNext();) {
                    PacientesR t = it.next();               
                    id=t.getId();
                    des=t.getDes();
                    fechaNac=t.getFechaNac();
                    edad=t.getEdad();
                    fechaAlta=t.getFechaAlta();
//                    JOptionPane.showMessageDialog(this, id+ des+ fechaNac+ edad+ fechaAlta);
                    pacList.add(new PacientesR(id, des, fechaNac, edad, fechaAlta));
//                    JOptionPane.showMessageDialog(this, pacList));
                }
            JasperReport report  = (JasperReport)JRLoader.loadObject(ClassLoader.getSystemResource("Reportes/ReportePac.jasper"));
            JasperPrint fillReport = JasperFillManager.fillReport(report, null,new JRBeanCollectionDataSource(pacList));
            JasperViewer jviewer = new JasperViewer(fillReport,false);
            jviewer.setTitle("Listado de pacientes.");
            jviewer.setVisible(true); 
        }else{
//            this.dispose();
            JOptionPane.showMessageDialog(this, "<html><font size=5>No hay información suficiente para generar el documento.");
        }  
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "<html><font size=5 style=color:red;>Error cargando reporte." + e);
    }
}

public int cantRegPac(){
        int num = 0;
        List<Paciente> lista = AbstractDAO.getListaEntidades(Paciente.class);
        for (Iterator<Paciente> it = lista.iterator(); it.hasNext();) {
            Paciente t = it.next();
            num = num + 1;
        }
        if(num==0){
            num=1;
        }
        return num;
    }












/**
* Método habilita o inhabilita todos los componentes
     * @param panel
     * @param op
*/
    public void EnableForm(Object panel, boolean op) {
        String nombre_clase = panel.getClass().getName();
        switch (nombre_clase) {
            case "javax.swing.JPanel":
                enablePanel((javax.swing.JPanel) panel, op);
                break;
            case "javax.swing.JScrollPane":
                enableScrollPane((javax.swing.JScrollPane) panel, op);
                break;
            case "javax.swing.JTabbedPane":
                enableTabbedPane((javax.swing.JTabbedPane) panel, op);
                break;
        }
    }

    private void enablePanel(javax.swing.JPanel panel, boolean op) {
        java.awt.Component[] componentes = panel.getComponents();
        for (Component componente : componentes) {
            enableComponent(componente, op);
        }
    }

    private void enableTabbedPane(javax.swing.JTabbedPane panel, boolean op) {
        java.awt.Component[] componentes = panel.getComponents();
        for (Component componente : componentes) {
            enableComponent(componente, op);
        }
    }
    
    private void enableScrollPane(javax.swing.JScrollPane panel, boolean op) {
        java.awt.Component[] componentes = panel.getViewport().getComponents();
        for (Component componente : componentes) {
            enableComponent(componente, op);
        }
    }

    private void enableComponent(java.awt.Component comp, boolean op) {
        String nombre_clase = comp.getClass().getName();
        switch (nombre_clase) {
            case "javax.swing.JTextField":
                ((javax.swing.JTextField) comp).setEnabled(op);
                break;
            case "javax.swing.JComboBox":
                ((javax.swing.JComboBox) comp).setEnabled(op);
                break;
            case "javax.swing.JTextArea":
                ((javax.swing.JTextArea) comp).setEnabled(op);
                break;
            case "javax.swing.JCheckBox":
                ((javax.swing.JCheckBox) comp).setEnabled(op);
                break;
            case "javax.swing.JRadioButton":
                ((javax.swing.JRadioButton) comp).setEnabled(op);
                break;
            case "javax.swing.JFormattedTextField":
                ((javax.swing.JFormattedTextField) comp).setEnabled(op);
                break;
            case "javax.swing.JLabel":
                ((javax.swing.JLabel) comp).setEnabled(op);
                break;
            case "javax.swing.JTable":
                ((javax.swing.JTable) comp).setEnabled(op);
                break;
            case "javax.swing.JButton":
                ((javax.swing.JButton) comp).setEnabled(op);
                break;
            case "javax.swing.JPanel":
                enablePanel((javax.swing.JPanel) comp, op);
                ((javax.swing.JPanel) comp).setEnabled(op);
                break;
            case "javax.swing.JScrollPane":
                enableScrollPane((javax.swing.JScrollPane) comp, op);
                ((javax.swing.JScrollPane) comp).setEnabled(op);
                break;
            case "javax.swing.JTabbedPane":
                enableTabbedPane((javax.swing.JTabbedPane) comp, op);
                ((javax.swing.JTabbedPane) comp).setEnabled(op);
                break;
        }
    } 
    
    private void SLetras(JTextField a){
        a.addKeyListener(new KeyAdapter() {
       @Override public void keyTyped(KeyEvent e) {            
            char car = e.getKeyChar();       
            if((car<'a' || car>'z') && (car<'A' || car>'Z')            
                && car !='á' //Minúsculas            
                && car !='é'           
                && car !='í'           
                && car !='ó'          
                && car !='ú'  
                && car !='Á' //Mayúsculas            
                && car !='É'           
                && car !='Í'           
                && car !='Ó'
                && car !='Ú'
                && car !='ñ'
                && car !='Ñ'    
                && (car!=(char)KeyEvent.VK_SPACE)
                && (car!=(char)KeyEvent.VK_BACK_SPACE)    
                    )
            {
              Toolkit.getDefaultToolkit().beep();
              e.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
                    JOptionPane.showMessageDialog(null, "<html><font size=5 style=color:red;>Solo puede ingresar letras", "Validando Datos",
                            JOptionPane.ERROR_MESSAGE);
              e.consume(); 
            }
            String text = ((JTextField) e.getSource()).getText();
            if (text.length() >= 40) {
                e.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
                JOptionPane.showMessageDialog(null, "<html><font size=5 style=color:red;>Ha excedido el número máximo de caracteres!!! (40)", "Validando Datos",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        });          
    }
    
    private void SNroEntero(JTextField a){   
        a.addKeyListener(new KeyAdapter() {
       @Override public void keyTyped(KeyEvent e) {            
		String text = ((JTextField) e.getSource()).getText();
		
                if(!Character.isDigit(e.getKeyChar()) && !Character.isISOControl(e.getKeyChar()))
                {
                     Toolkit.getDefaultToolkit().beep();

                     e.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
                    JOptionPane.showMessageDialog(null, "<html><font size=5 style=color:red;>Solo puede ingresar números", "Validando Datos",
                            JOptionPane.ERROR_MESSAGE);
                    e.consume();
                }

                //Limitar el numero de caracteres. Solo se pueden ingresar 5 caracteres
                if (text.length() >= 5) {
                    e.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
                    JOptionPane.showMessageDialog(null, "<html><font size=5 style=color:red;>Ha excedido el numero maximo de caracteres!!! (5)", "Validando Datos",
                            JOptionPane.ERROR_MESSAGE);
                }                     
        }
        });  
    }



}
