/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.AbstractDAO;
import Controlador.OcupacionDAO;
import Controlador.PacientesDAO;
import Modelo.Paciente;
import Modelo.Ocupacion;
import static Vista.iFraAdm.createImageIcon;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import util.Fecha;
import util.modalInternalFrame;
import util.validatorUtil;


/**
 *
 * @author usuario
 */
public class iFraPaciente extends modalInternalFrame {
    private DefaultTableModel model;
    ImageIcon icon = createImageIcon("img/middle.gif");
    PacientesDAO pacientesDAO = null;
    OcupacionDAO ocupacionDAO= null;
    Fecha fecha = null;
    private int num;
    /**
     * Creates new form iFraPaciente
     */
    public iFraPaciente() {
        initComponents();
        arranque();
        grupoBotones();
        SLetras(txtApellido);
        SLetras(txtId);
        SLetras(txtNombre);
        SLetras(txtNombreBuscar);  
        SNroEntero(this.txtIdBuscar);
        SNroEntero(this.txtTelefono);
//        fecha = new Fecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelEncabezado = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblEdad5 = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JTextField();
        panelBuscar = new javax.swing.JPanel();
        txtIdBuscar = new javax.swing.JTextField();
        txtNombreBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rbtNombre = new javax.swing.JRadioButton();
        rbtNro = new javax.swing.JRadioButton();
        panelDatosPaciente = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelDatos = new javax.swing.JPanel();
        panelDatosPersonales = new javax.swing.JPanel();
        cboOcupacion = new javax.swing.JComboBox();
        lblEdad2 = new javax.swing.JLabel();
        lblEdad3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblEdad1 = new javax.swing.JLabel();
        cboSexo = new javax.swing.JComboBox();
        lblEdad4 = new javax.swing.JLabel();
        cboEstadoCivil = new javax.swing.JComboBox();
        txtEdad = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        btnAddOcupacion = new javax.swing.JButton();
        txtFechaNac = new com.toedter.calendar.JDateChooser();
        jPanelContacto = new javax.swing.JPanel();
        panelDatosContacto = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtCel = new javax.swing.JFormattedTextField();
        panelBotones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnInforme = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pacientes");
        setToolTipText("");
        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        panelEncabezado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/paciente.png"))); // NOI18N
        lblTitulo.setText("      FORMULARIO DE PACIENTES");

        lblEdad5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblEdad5.setText("Fecha");

        txtFechaIngreso.setEditable(false);
        txtFechaIngreso.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtFechaIngreso.setText("_/_/____");
        txtFechaIngreso.setBorder(null);
        txtFechaIngreso.setEnabled(false);

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEdad5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad5))
                .addContainerGap())
        );

        panelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        panelBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtIdBuscar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N

        txtNombreBuscar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/search-16.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nro", "Apellido", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        rbtNombre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        rbtNombre.setText("Apellido y Nombre");
        rbtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNombreActionPerformed(evt);
            }
        });

        rbtNro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        rbtNro.setText("Número");
        rbtNro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBuscarLayout.createSequentialGroup()
                            .addComponent(rbtNro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIdBuscar))
                        .addComponent(rbtNombre, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtNro))
                .addGap(1, 1, 1)
                .addComponent(rbtNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelDatosPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        panelDatosPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTabbedPane.setAutoscrolls(true);
        jTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanelDatos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cboOcupacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboOcupacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Soltero", "Casado" }));

        lblEdad2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEdad2.setText("Profesión/Ocupación");

        lblEdad3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEdad3.setText("Fecha Nacimiento");

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nro");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Apellido");

        lblEdad1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEdad1.setText("Sexo");

        cboSexo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Femenino", "Masculino" }));

        lblEdad4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEdad4.setText("Estado civil");

        cboEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Casada/o", "Soltera/o", "Separada/o", "Viuda/o" }));

        txtEdad.setEditable(false);
        txtEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEdad.setText("Edad");

        btnAddOcupacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddOcupacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/24_add.png"))); // NOI18N
        btnAddOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOcupacionActionPerformed(evt);
            }
        });

        txtFechaNac.setDateFormatString("dd/MM/yyyy");
        txtFechaNac.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFechaNac.setMaxSelectableDate(new java.util.Date(32503694480000L));
        txtFechaNac.setMinSelectableDate(new java.util.Date(-2208974320000L));
        txtFechaNac.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFechaNacPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panelDatosPersonalesLayout = new javax.swing.GroupLayout(panelDatosPersonales);
        panelDatosPersonales.setLayout(panelDatosPersonalesLayout);
        panelDatosPersonalesLayout.setHorizontalGroup(
            panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellido)
                                    .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 276, Short.MAX_VALUE))))
                            .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEdad3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaNac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEdad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEdad1)
                                    .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPersonalesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPersonalesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEdad4)
                                    .addComponent(cboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(cboOcupacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addContainerGap())
            .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEdad2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosPersonalesLayout.setVerticalGroup(
            panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad1)
                    .addComponent(lblEdad)
                    .addComponent(lblEdad3)
                    .addComponent(lblEdad4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboEstadoCivil))
                    .addComponent(txtFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(lblEdad2)
                        .addGap(4, 4, 4)
                        .addComponent(cboOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Datos personales", jPanelDatos);

        jPanelContacto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Teléfono");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Email");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Celular");

        try {
            jtxtCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtCel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelDatosContactoLayout = new javax.swing.GroupLayout(panelDatosContacto);
        panelDatosContacto.setLayout(panelDatosContactoLayout);
        panelDatosContactoLayout.setHorizontalGroup(
            panelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosContactoLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(panelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail)
                    .addGroup(panelDatosContactoLayout.createSequentialGroup()
                        .addGroup(panelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtCel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(156, 156, 156)))
                .addGap(103, 103, 103))
        );

        panelDatosContactoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel7});

        panelDatosContactoLayout.setVerticalGroup(
            panelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosContactoLayout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(panelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(14, 14, 14))
        );

        panelDatosContactoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5, jtxtCel, txtTelefono});

        panelDatosContactoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel7, txtEmail});

        javax.swing.GroupLayout jPanelContactoLayout = new javax.swing.GroupLayout(jPanelContacto);
        jPanelContacto.setLayout(jPanelContactoLayout);
        jPanelContactoLayout.setHorizontalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContactoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelDatosContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelContactoLayout.setVerticalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(panelDatosContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Datos de contacto", jPanelContacto);

        javax.swing.GroupLayout panelDatosPacienteLayout = new javax.swing.GroupLayout(panelDatosPaciente);
        panelDatosPaciente.setLayout(panelDatosPacienteLayout);
        panelDatosPacienteLayout.setHorizontalGroup(
            panelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDatosPacienteLayout.setVerticalGroup(
            panelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosPacienteLayout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBotones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/New.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Trashcan_empty.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnInforme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Tasks.png"))); // NOI18N
        btnInforme.setText("Informe");
        btnInforme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInforme.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/cancel32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInforme, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar)
                    .addComponent(btnNuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBotonesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnEditar, btnEliminar, btnGuardar, btnInforme, btnNuevo});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDatosPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {panelBotones, panelBuscar, panelDatosPaciente, panelEncabezado});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatosPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        tableModel();
        if(this.rbtNro.isSelected())
        {
            if(txtIdBuscar.getText().trim().length()!=0)
                cargarTabla(1);
            else {JOptionPane.showMessageDialog(this, "<html><font size=5>Ingrese un Nro a buscar..");
                txtIdBuscar.grabFocus(); }
        }
        else{
            if(txtNombreBuscar.getText().trim().length()!=0)
                cargarTabla(2);
            else {JOptionPane.showMessageDialog(this, "<html><font size=5>Ingrese un nombre a buscar..");
                txtNombreBuscar.grabFocus(); }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        cargarPaciente();
    }//GEN-LAST:event_jTable1MouseClicked

    private void rbtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNombreActionPerformed
        // TODO add your handling code here:
        habilitarBusqueda(false);
    }//GEN-LAST:event_rbtNombreActionPerformed

    private void rbtNroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNroActionPerformed
        // TODO add your handling code here:
        habilitarBusqueda(true);
    }//GEN-LAST:event_rbtNroActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevo();
        this.panelBuscar.setVisible(false);
        this.setSize(840, 600);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editar();
        this.panelBuscar.setVisible(false);
        this.setSize(840, 600);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeActionPerformed
        //informe();
        Frame f = JOptionPane.getFrameForComponent(this);
        dlgPacOpReporte dialog = new dlgPacOpReporte(f, true);
//        dialog.setOpcion(4);
        dialog.show();
    }//GEN-LAST:event_btnInformeActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        arranque();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAddOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOcupacionActionPerformed
                
        JTextField textField = new JTextField();
        SLetras(textField);
        Object[] msj = {"Ingrese nombre: ", textField};
        
        Object[] opciones={ "Guardar", "Cancelar"};
        int op=JOptionPane.showOptionDialog(null, 
                msj, //Mensaje
                "Registrar Nueva ocupación o profesión", 
                JOptionPane.DEFAULT_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, 
                null, 
                opciones, 
                opciones[0]);
        
        switch(op) { 
           case 0: // Guardar
               if ((textField.getText().trim()).length()!=0) {         
                    Ocupacion oc = new Ocupacion();
                    oc.setDes(textField.getText());
                    AbstractDAO.almacenaEntidad(oc);           
                    JOptionPane.showInternalMessageDialog(this,"<html><font size=5>Registro guardado. Nombre: " + textField.getText() + "!");
                    cargarCombo();
                }else
                   JOptionPane.showMessageDialog(this,"<html><font size=5 style=color:red;>No se guardo el registro. Campo vacio.");
             break; 
           case 1: // Cancelar 
             break; 
           default: 
             break; 
        } 
        
//        limpiarVentanas();
//        iFraOcupacion p=new iFraOcupacion();
//        p.setModal(true); 
//        p.nuevo();
//        fraMenu.getEscritorio().add(p);
//        centrarVentanas();
//        p.show();
//        cargarCombo();
//        p.dispose();
////      cboHorario.setSelectedIndex(-1);
    }//GEN-LAST:event_btnAddOcupacionActionPerformed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped

        if (txtEmail.getText().length() >= 35) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
            JOptionPane.showMessageDialog(null, "<html><font size=5 style=color:red;>Ha excedido el número máximo de caracteres!!! (35)", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtFechaNacPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFechaNacPropertyChange
        if(txtFechaNac.getDate()!=null){
            if(fecha.checkFecha(txtFechaNac)){
            this.txtEdad.setText(String.valueOf(fecha.edad(fecha.getStringXfecha(txtFechaNac.getDate()))));
            }else txtFechaNac.setDate(null);
        }
        
    }//GEN-LAST:event_txtFechaNacPropertyChange

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()))
        {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        //int k = (int) evt.getKeyChar();
        if (txtTelefono.getText().length() >= 20) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
            JOptionPane.showMessageDialog(null, "<html><font size=5 style=color:red;>Ha excedido el número máximo de caracteres!!! (20)", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOcupacion;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInforme;
    private javax.swing.JButton btnNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboEstadoCivil;
    private javax.swing.JComboBox cboOcupacion;
    private javax.swing.JComboBox cboSexo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelContacto;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField jtxtCel;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEdad1;
    private javax.swing.JLabel lblEdad2;
    private javax.swing.JLabel lblEdad3;
    private javax.swing.JLabel lblEdad4;
    private javax.swing.JLabel lblEdad5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelDatosContacto;
    private javax.swing.JPanel panelDatosPaciente;
    private javax.swing.JPanel panelDatosPersonales;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JRadioButton rbtNombre;
    private javax.swing.JRadioButton rbtNro;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFechaIngreso;
    private com.toedter.calendar.JDateChooser txtFechaNac;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdBuscar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    
private void arranque(){
//    txtFechaNac.setDateFormatString(fecha.);
    cargarCombo();
    comboSexo();
    comboEstadoCivil();
    this.rbtNro.setSelected(true);
    habilitarBusqueda(true);
    habilitarCampos(false);
    limpiarCampos();
    //btnAddOcupacion.setEnabled(false);
    this.btnGuardar.setEnabled(false);
    this.btnEditar.setEnabled(false);
    this.btnEliminar.setEnabled(false);
    this.btnInforme.setEnabled(true);
    this.btnNuevo.setEnabled(true);
    this.btnGuardar.setText("Guardar");
    this.jTable1.setEnabled(true);
    tableModel();
    //cargarTabla();
    //tam original ventana
    this.panelBuscar.setVisible(true);
    this.setSize(840, 800);
    //
    //Calendar cal = Calendar.getInstance();    
    //String calString = retornarString(cal);
    fecha = new Fecha();
    String calString=fecha.getString();
    this.txtFechaIngreso.setText(calString);
    jTabbedPane.setSelectedIndex(0);
}

public void tableModel(){
    this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
    this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(90);
    this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(90);
    jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.ITALIC, 18));
    jTable1.setFont(new Font("Segoe UI", Font.PLAIN, 18));
    jTable1.setRowHeight(30);
    model = (DefaultTableModel)this.jTable1.getModel();
    model.setNumRows(0);
}
public void cargarCombo(){
    this.cboOcupacion.removeAllItems();
    List<Ocupacion> lista =AbstractDAO.getListaEntidadesByDesc(Ocupacion.class);
    for(Ocupacion ocupaList : lista){
        this.cboOcupacion.addItem(ocupaList.getDes());
    }
}

private void habilitarBusqueda(boolean op){
        this.txtNombreBuscar.setEnabled(!op);
        this.txtIdBuscar.setEnabled(op);
        this.txtIdBuscar.setText(null);
        this.txtNombreBuscar.setText(null);
        if(op) this.txtIdBuscar.grabFocus();
        if(!op) this.txtNombreBuscar.grabFocus();
        tableModel();
}

public void cargarTabla(int op){
    List<Paciente> lista = null;
    if (op==1){ 
        int cod = Integer.parseInt(txtIdBuscar.getText());    
        lista=AbstractDAO.getListaEntidadesXid(Paciente.class, cod);
    }
    else {
        String nom = txtNombreBuscar.getText();
        pacientesDAO = new PacientesDAO();
        lista=pacientesDAO.getPacientesXnonApe(nom);
    }
    for (Iterator<Paciente> it = lista.iterator(); it.hasNext();) {
            Paciente pac = it.next();
            model.addRow(new Object[]{
                pac.getId(),pac.getApellido(),pac.getNombre()
            });
        } 
    
    if(lista.isEmpty())JOptionPane.showMessageDialog(this, "<html><font size=5>Esta búsqueda no arrojo resultados..");
}

public void comboSexo(){
    this.cboSexo.removeAllItems();
    this.cboSexo.addItem("Femenino");
    this.cboSexo.addItem("Masculino");
}

public void comboEstadoCivil(){
    this.cboEstadoCivil.removeAllItems();
    this.cboEstadoCivil.addItem("Soltera/o");
    this.cboEstadoCivil.addItem("Casada/o");
    this.cboEstadoCivil.addItem("Viuda/o");
}

public void habilitarCampos(boolean op){    
    this.txtId.setEnabled(op);
    this.txtApellido.setEnabled(op);
    this.txtNombre.setEnabled(op);
    this.txtFechaNac.setEnabled(op);
    this.txtEdad.setEnabled(op);
    this.cboOcupacion.setEnabled(op);
    this.cboSexo.setEnabled(op);
    this.cboEstadoCivil.setEnabled(op);
    this.txtEmail.setEnabled(op);
    this.txtTelefono.setEnabled(op);
    jtxtCel.setEnabled(op);
    btnAddOcupacion.setEnabled(op);
    this.jtxtCel.setEditable(op);
}

public void limpiarCampos(){    
    this.txtId.setText(null);
    this.txtApellido.setText(null);
    this.txtNombre.setText(null);
//    this.txtFechaNac.setText(null);
    txtFechaNac.setDate(null);
    this.txtEdad.setText(null);
    this.cboOcupacion.setSelectedIndex(-1);
    this.cboSexo.setSelectedIndex(-1);
    this.cboEstadoCivil.setSelectedIndex(-1);
    this.txtEmail.setText(null);
    this.txtTelefono.setText(null);
    jtxtCel.setText(null);
}

public void nuevo(){
    obtenetID();
    habilitarCampos(true);
    this.btnNuevo.setEnabled(false);
    this.btnGuardar.setEnabled(true);
//    this.txtId.setText("Auto");
    this.txtId.setText(String.valueOf(num));
    this.txtNombre.grabFocus();
}

public void obtenetID(){
    num = 0;
    List<Paciente> lista = AbstractDAO.getListaEntidades(Paciente.class);
    for (Iterator<Paciente> it = lista.iterator(); it.hasNext();) {
        Paciente d = it.next();
        num= d.getId() + 1;
    }
    if(num==0){
        num=1;
    } 
}

private void grupoBotones(){
        this.buttonGroup1=new ButtonGroup();
        this.buttonGroup1.add(rbtNro);
        this.buttonGroup1.add(rbtNombre); //btnGroupPac
}

public void eliminar(){
   int showConfirmDialog = JOptionPane.showConfirmDialog(this, "<html><font size=5>¿Desea eliminar el Registro?", "Eliminación de Registro.", JOptionPane.YES_NO_OPTION);
   if(showConfirmDialog == 1){
       JOptionPane.showMessageDialog(this, "<html><font size=5>Registro no eliminado.");
   }
   else{
       int idPac = getId();
       Paciente pac = AbstractDAO.getEntidad(idPac, Paciente.class);
       AbstractDAO.borrarEntidad(pac);
       JOptionPane.showMessageDialog(this, "<html><font size=5 style=color:red;>Registro eliminado.");
       arranque();
   }
}

private int getId(){
    int selectedRow = this.jTable1.getSelectedRow();
    Object valueAt = model.getValueAt(selectedRow, 0);
    int id = Integer.parseInt(valueAt.toString());
    return id;
}

public void editar(){    
    //Activo los campos q puedo editar
    habilitarCampos(true);
    this.btnGuardar.setEnabled(true);
    this.btnGuardar.setText("Actualizar");
    this.btnEliminar.setEnabled(false);
    this.btnEditar.setEnabled(false);
    this.jTable1.setEnabled(false);
    
}

public void cargarPaciente(){// EN LOS COMPONENTES PARA LUEGO EDITAR
    if(this.jTable1.isEnabled()){
        int idPac = getId();
        Paciente pac = AbstractDAO.getEntidad(idPac, Paciente.class);
        
        fecha = new Fecha();      
        String fechaIngreso = fecha.retornarString(pac.getFechaIngreso());              
//        String fechaNac = fecha.retornarString(pac.getFechaNac()); 
        this.txtFechaIngreso.setText(fechaIngreso); 
//        this.txtFechaNac.setText(fechaNac);
        txtFechaNac.setDate(fecha.getCalendarToDate(fecha.retornarString(pac.getFechaNac())));
        this.txtEdad.setText(String.valueOf(pac.getEdad()));
        this.txtId.setText(String.valueOf(pac.getId()));
        this.txtApellido.setText(pac.getApellido());
        this.txtNombre.setText(pac.getNombre());        
        this.cboOcupacion.setSelectedItem(pac.getOcupacion().getDes());
        this.txtEmail.setText(pac.getEmail());
        this.txtTelefono.setText(pac.getTelefono());
        this.jtxtCel.setText(pac.getCelular());
        this.cboSexo.setSelectedItem(pac.getSexo());
        this.cboEstadoCivil.setSelectedItem(pac.getEstadoCivil());
        this.btnEditar.setEnabled(true);
        this.btnEliminar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
    }    
}

public void guardar(){
    if(!validar()){
        //JOptionPane.showMessageDialog(null, "Imposible guardar hay campos vacios.");
    }
    else{
        if(this.btnGuardar.getText().equals("Guardar")){
            int selectedIndex = this.cboOcupacion.getSelectedIndex()+1;//Si elimino esto deja de andar
            Ocupacion retornoOcupacion = AbstractDAO.getEntidad(selectedIndex, Ocupacion.class);  
            Paciente pac = new Paciente();
            
            fecha=new Fecha();
            Calendar fechaIngreso = fecha.retornarCalendar(txtFechaIngreso.getText());
//            Calendar fechaNac = fecha.retornarCalendar(txtFechaNac.getText());
            Calendar fechaNac = fecha.retornarCalendar(fecha.getStringXfecha(txtFechaNac.getDate()));
            pac.setFechaIngreso(fechaIngreso);
            pac.setFechaNac(fechaNac);
            pac.setEdad(fecha.edad(fecha.retornarString(fechaNac)));        
//            pac.setEdad(Integer.parseInt(txtEdad.getText()));
            pac.setNombre(txtNombre.getText());
            pac.setApellido(txtApellido.getText());           
            pac.setEmail(txtEmail.getText());
            pac.setTelefono(txtTelefono.getText());
            pac.setCelular(jtxtCel.getText());
            pac.setOcupacion(retornoOcupacion);            
            pac.setSexo(String.valueOf(this.cboSexo.getSelectedItem()));
            pac.setEstadoCivil(String.valueOf(this.cboEstadoCivil.getSelectedItem()));
            AbstractDAO.almacenaEntidad(pac);
            
            JOptionPane.showMessageDialog(this, "<html><font size=5>Registro guardado.");
            arranque();
        }
        else{         
            int idPac = getId();//toma el id de la tabla
            Paciente pac = AbstractDAO.getEntidad(idPac, Paciente.class);;//retorna el Pac para ese id
            String selectedItem = this.cboOcupacion.getSelectedItem().toString();
            ocupacionDAO = new OcupacionDAO();
            Ocupacion retornoOcupacion = ocupacionDAO.getOcupacion(selectedItem);//retorna la Ocupa con esa desc 
            pac.setOcupacion(retornoOcupacion);
            
            fecha=new Fecha();
//            Calendar fechaNac = fecha.retornarCalendar(txtFechaNac.getText());
            Calendar fechaNac = fecha.retornarCalendar(fecha.getStringXfecha(txtFechaNac.getDate()));
            Calendar fechaIngreso = fecha.retornarCalendar(txtFechaIngreso.getText());            

            pac.setFechaNac(fechaNac);
            pac.setFechaIngreso(fechaIngreso);
            pac.setEdad(fecha.edad(fecha.retornarString(fechaNac))); 
//            pac.setEdad(Integer.parseInt(txtEdad.getText()));
            pac.setNombre(txtNombre.getText());
            pac.setApellido(txtApellido.getText());           
            pac.setEmail(txtEmail.getText());
            pac.setTelefono(txtTelefono.getText());           
            pac.setCelular(jtxtCel.getText());
            pac.setSexo(String.valueOf(this.cboSexo.getSelectedItem()));
            pac.setEstadoCivil(String.valueOf(this.cboEstadoCivil.getSelectedItem()));           
            AbstractDAO.almacenaEntidad(pac);
            JOptionPane.showMessageDialog(this, "<html><font size=5>Registro actualizado.");
            arranque();
        }
    }
}

public boolean validar(){
    String tit="Atención"; String msj; 
    boolean res=true;
        
    if((txtNombre.getText().trim()).length()==0)
    {   msj="<html><font size=5 style=color:red;>Nombre. Dato Requerido";
        JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
        txtNombre.grabFocus();
        return false;
    }

    if((txtApellido.getText().trim()).length()==0)
    {   msj="<html><font size=5 style=color:red;>Apellido. Dato Requerido";
        JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
        txtApellido.grabFocus();
        return false;
    }
    //FechaNacimiento
//    if((this.txtFechaNac.getText().trim()).length()==4)
//      {   msj="<html><font size=5 style=color:red;>Fecha Nacimiento. Dato Requerido.";
//          JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
//          txtFechaNac.grabFocus();
//          return false;
//      }
    if(this.txtFechaNac.getDate()==null)
      {   msj="<html><font size=5 style=color:red;>Fecha Nacimiento. Dato Requerido.";
          JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
          txtFechaNac.grabFocus();
          return false;
      }
    if(!fecha.checkFecha(txtFechaNac))
     {   msj="<html><font size=5 style=color:red;>Revise Fecha Nac.";
          JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
          txtFechaNac.grabFocus();
          return false;
      }
    //Edad se calcula
//    if((txtEdad.getText().trim()).length()==0 || Integer.parseInt(txtEdad.getText())==0 )
//    {   msj="<html><font size=5 style=color:red;>Edad. Dato Requerido. ";
//        JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
//        txtFechaNac.grabFocus();
//        return false;
//    }
    //Sexo
    if(this.cboSexo.getSelectedIndex()==-1)
      {   msj="<html><font size=5 style=color:red;>Sexo. Dato Requerido";
        JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
          cboSexo.grabFocus();
          return false;
      }
    //Profesion
    //this.cboOcupacion.setSelectedIndex(-1)
    if(this.cboOcupacion.getSelectedIndex()==-1)
      {   msj="<html><font size=5 style=color:red;>Ocupación/Profesión. Dato Requerido";
        JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
          cboOcupacion.grabFocus();
          return false;
      }
    //Estado civil
    if(this.cboEstadoCivil.getSelectedIndex()==-1)
      {   msj="<html><font size=5 style=color:red;>Estado civil. Dato Requerido";
      JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
          cboEstadoCivil.grabFocus();
          return false;
      }
    
    if((this.txtEmail.getText().trim()).length()!=0){
        boolean op=validatorUtil.validateEmail(this.txtEmail.getText());
        if(!op){
            msj="<html><font size=5 style=color:red;>El email no tiene un formato válido.";
            JOptionPane.showMessageDialog(this, msj,tit,JOptionPane.WARNING_MESSAGE);
            txtEmail.grabFocus();
            return false;
        }  
    }
    
//    if((this.txtTelefono.getText().trim()).length()!=0){
//        boolean op=validatorUtil.validateTel(this.txtTelefono.getText());
//        if(!op){
//            JOptionPane.showMessageDialog(this, "El Teléfono no tiene un formato válido.");
//            txtTelefono.grabFocus();
//            return false;
//        }  
//    }
    
    return res;
}

//private void limpiarVentanas(){
//    int cant=fraMenu.getEscritorio().getAllFrames().length;
//    JInternalFrame internalFrames[] = fraMenu.getEscritorio().getAllFrames();
//    for (int i=0; i<cant; i++) {        
//        if(!internalFrames[i].getTitle().equals("Pacientes")){
//            internalFrames[i].dispose();
//        }
//    }
//}
    
public void centrarVentanas(){
    int x,y,cant;
    cant=fraMenu.getEscritorio().getAllFrames().length;
    JInternalFrame internalFrames[] = fraMenu.getEscritorio().getAllFrames();
    for (int i=0; i<cant; i++) {         
        if(!internalFrames[i].getTitle().equals("Pacientes")){
            x = (fraMenu.getEscritorio().getWidth()/2) - internalFrames[i].getWidth()/2;
            y = (fraMenu.getEscritorio().getHeight()/2) - internalFrames[i].getHeight()/2;
            internalFrames[i].setLocation(x, y);
        }
    }
}

private void SLetras(JTextField a){
        a.addKeyListener(new KeyAdapter() {
       @Override public void keyTyped(KeyEvent e) {            
            char car = e.getKeyChar();       
            if((car<'a' || car>'z') && (car<'A' || car>'Z')            
                && car !='á' //Minúsculas            
                && car !='é'           
                && car !='í'           
                && car !='ó'          
                && car !='ú'  
                && car !='Á' //Mayúsculas            
                && car !='É'           
                && car !='Í'           
                && car !='Ó'
                && car !='Ú'
                && car !='ñ'
                && car !='Ñ'    
                && (car!=(char)KeyEvent.VK_SPACE)
                && (car!=(char)KeyEvent.VK_BACK_SPACE)    
                    )
            {
              Toolkit.getDefaultToolkit().beep();
              e.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
                    JOptionPane.showMessageDialog(null, "<html><font size=5 style=color:red;>Solo puede ingresar letras", "Validando Datos",
                            JOptionPane.ERROR_MESSAGE);
              e.consume(); 
            }
            String text = ((JTextField) e.getSource()).getText();
            if (text.length() >= 50) {
                e.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
                JOptionPane.showMessageDialog(null, "<html><font size=5 style=color:red;>Ha excedido el número máximo de caracteres!!! (50)", "Validando Datos",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        });          
    }

private void SNroEntero(JTextField a){   
        a.addKeyListener(new KeyAdapter() {
       @Override public void keyTyped(KeyEvent e) {            
		String text = ((JTextField) e.getSource()).getText();
		
                if(!Character.isDigit(e.getKeyChar()) && !Character.isISOControl(e.getKeyChar()))
                {
                     Toolkit.getDefaultToolkit().beep();

                     e.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
                    JOptionPane.showMessageDialog(null, "<html><font size=5 style=color:red;>Solo puede ingresar números", "Validando Datos",
                            JOptionPane.ERROR_MESSAGE);
                    e.consume();
                }

                //Limitar el numero de caracteres. Solo se pueden ingresar 5 caracteres
                if (text.length() >= 15) {
                    e.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
                    JOptionPane.showMessageDialog(null, "<html><font size=5 style=color:red;>Ha excedido el numero maximo de caracteres!!! (15)", "Validando Datos",
                            JOptionPane.ERROR_MESSAGE);
                }                     
        }
        });  
    }


}
