/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.AbstractDAO;
import Controlador.conexion;
import Modelo.Usuario;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author usuario
 */
public class login extends javax.swing.JFrame {
    private Timer tiempo;
    int cont;
    public final static int TWO_SECOND=5;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        barrita.setVisible(false);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("img/icoApp.png"));
        setIconImage(icon);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        ptxtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        barrita = new javax.swing.JProgressBar();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Terapia Psicológica");
        setIconImages(getIconImages());
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(50, 172, 156));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Password_protection.png"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 12, 60, 58));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("IDENTIFICATE");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 12, 203, 59));

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 335, -1));

        ptxtPass.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        ptxtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ptxtPassKeyPressed(evt);
            }
        });
        jPanel1.add(ptxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 104, 335, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 11, 111, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 75, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/pc160.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 201));

        btnCancelar.setBackground(new java.awt.Color(0, 153, 51));
        btnCancelar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnCancelar.setText("Salir");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 154, -1));

        btnIngresar.setBackground(new java.awt.Color(73, 174, 80));
        btnIngresar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 155, -1));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 77, 542, -1));

        barrita.setBackground(new java.awt.Color(204, 204, 255));
        barrita.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        barrita.setForeground(new java.awt.Color(255, 51, 0));
        jPanel5.add(barrita, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 284, 522, 19));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
//       inicioSesion();  
        if(validar()){
           //verificar si existe este usu y pass en BD
           String usu, pass;
           usu=this.txtUsuario.getText();
           pass=this.ptxtPass.getText();
//           pass=DigestUtils.md5Hex(pass); //Encriptado!!
           boolean op = conexion.getInstance().verificarUsuario(usu, pass);
//           AbstractDAO.getEntidad(1, Usuario.class);
           if(op){ //Llamo al otro fra y salgo de este
                barrita.setVisible(true);    
                cont=1;
                barrita.setValue(0);
                barrita.setStringPainted(true);   
                tiempo= new Timer(TWO_SECOND,new TimerListener());
                activar();
               AbstractDAO.getEntidad(1, Usuario.class);
//               fraMenu mnu=new fraMenu();
//               mnu.setVisible(true);
//               this.dispose();
           } else{
               String mensaje="<html><h2 style=color:red;>Usuario o Clave incorrectos.</h2></html>";
               JOptionPane.showMessageDialog(this, mensaje, "ERROR",JOptionPane.ERROR_MESSAGE);           
           }
       }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void ptxtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptxtPassKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            inicioSesion();
        }
    }//GEN-LAST:event_ptxtPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barrita;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField ptxtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

  
  public boolean validar(){
    
    boolean res=true; String mnsj, tit;
    tit="Atención";    
    if((txtUsuario.getText().trim()).length()==0)
    {   mnsj="<html><h2 style=color:red;>Usuario. Dato Requerido.</h2></html>";
        
        JOptionPane.showMessageDialog(this, mnsj,tit,JOptionPane.WARNING_MESSAGE);
        txtUsuario.grabFocus();
        return false;
    }

    if((ptxtPass.getText().trim()).length()==0)
    {   mnsj="<html><h2 style=color:red;>Clave. Dato Requerido.</h2></html>";
        JOptionPane.showMessageDialog(this, mnsj,tit,JOptionPane.WARNING_MESSAGE);
        
        ptxtPass.grabFocus();
        return false;
    }
    
    return res;
}
  
//  @Override
//    public Image getIconImage() {
//       Image retValue = Toolkit.getDefaultToolkit().
//    //         getImage(ClassLoader.getSystemResource("Vista/img/24_add.png"));
//               getImage(ClassLoader.getSystemResource("Vista/img/icoApp.png"));
//       return retValue;
//    }
    
  class TimerListener implements ActionListener{
      
      @Override
      public void actionPerformed(ActionEvent e){
          cont++;
          barrita.setValue(cont);
          if(cont==100){
              tiempo.stop();
              esconder();
              fraMenu mnu=new fraMenu();
              mnu.setVisible(true);
              setVisible(false);
//              this.dispose();
          } 
//          throw new UnsupportedOperationException("Not supported yet.");
      }
  }
  
  public void esconder(){this.setVisible(false);}
  public void activar(){tiempo.start();}
  
    public void inicioSesion(){
        String usu=txtUsuario.getText();
        String pass=String.valueOf(ptxtPass.getPassword());
        
        if(usu.equals("erika") && pass.compareTo("1234")==0){
            barrita.setVisible(true);    
            cont=1;
            barrita.setValue(0);
            barrita.setStringPainted(true);   
            tiempo= new Timer(TWO_SECOND,new TimerListener());
            activar();
            
            AbstractDAO.getEntidad(1, Usuario.class);
               
        } else{
               String mensaje="<html><h2 style=color:red;>Error al ingresar, usuario o contraseña incorrectas.</h2></html>";
               JOptionPane.showMessageDialog(this, mensaje, "ERROR",JOptionPane.ERROR_MESSAGE);           
           }
    }

}
